version: '3.5'
services:
    #BGL Service in Go
    test-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${APP_NAME}
        container_name: ${APP_NAME}
        restart: unless-stopped
        tty: true
        ports:
          - '${DOCKER_CONTAINER_PORT}:${APP_PORT}'
        environment:
            SERVICE_NAME: ${APP_NAME}
            SERVICE_TAGS: dev
        networks:
            - bgl

    #Mariadb Service
    mariadb:
        image: mariadb:10.5.1-bionic
        container_name: ${APP_NAME}_mariadb
        restart: unless-stopped
        tty: true
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - bgl

#Docker Networks
networks:
    bgl:
        name: bgl
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local